### ISSUE TITLE
Feed, please

### ISSUE THREAD

**Issue by whtsky** [wangxiyu191/wangxiyu191.github.com#1]
😿

**Comment by wangxiyu191** [comment]
too busy...
I will try to finish it in ths week.

**Comment by whtsky** [comment]
T_T

Then how can I read inspiring articles from my favorite person, Wang Xiyu, known as the most lihai programmer in the world as soon as he publish a new one?


2016年5月9日 +0800 PM3:19 wangxiyu191<notifications@github.com>，写道：

**Comment by whtsky** [comment]
QAQ

**Comment by wangxiyu191** [comment]
finished https://github.com/wangxiyu191/blogo/commit/6585ce1395ddf9d83ee4cf54e1b3368a42a02cc6
